import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./sections/Navbar";
import Footer from "./sections/Footer";
import ResponsiveScaler from "./appComponents/ResponsiveScaler";
import { StoreProvider } from "./redux/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ResponsiveScaler>
          <StoreProvider>
            <main className="app-content">
              <Navbar />
              <div className="content-container">{children}</div>

              <Footer />
            </main>
          </StoreProvider>
        </ResponsiveScaler>
      </body>
    </html>
  );
}
